In [1]:
import numpy as np

In [2]:
def fun1(*args, **kwargs):
    # args is a list of accumulated unnamed parameters
    # kwargs is a dict of named parameters
    print(tuple(args))
    for arg in args:
        print("Next argument through *argv :", arg)
        
    for key, value in kwargs.items():
        print("%s == %s" % (key, value))

In [3]:
fun1(4, 5, 3, 10)

(4, 5, 3, 10)
Next argument through *argv : 4
Next argument through *argv : 5
Next argument through *argv : 3
Next argument through *argv : 10


In [4]:
fun1(4, 3, a =  2, p = 0)

(4, 3)
Next argument through *argv : 4
Next argument through *argv : 3
a == 2
p == 0


In [5]:
def fun2(*args, **kwargs):
    
    fun1(*args, **kwargs)

In [6]:
fun2(4, 3, a =  2, p = 0)

(4, 3)
Next argument through *argv : 4
Next argument through *argv : 3
a == 2
p == 0


### testing out broadcasting in 4 dimensions

In [7]:
p = np.random.randint(1, 10, size = (3, 4, 5, 6))

In [8]:
c = np.random.randint(1, 5, size = (4, 2, 3))

In [9]:
p[:, :, 1:3, 2:5].shape

(3, 4, 2, 3)

In [10]:
# Does this work ?
actual = p[:, :, 1:3, 2:5] + c

In [11]:
actual.shape

(3, 4, 2, 3)

In [12]:
n, _, _, _ = p.shape
expected = np.copy(p[:, :, 1:3, 2:5])
for i in range(n):
    expected[i, :] += c

In [13]:
expected.shape

(3, 4, 2, 3)

In [14]:
np.linalg.norm(expected - actual)

0.0

## isinstance

In [15]:
isinstance((3, 2), tuple)

True

In [16]:
isinstance(3, tuple)

False

In [17]:
len((3, 45))

2

In [18]:
(4, *(3, 3))

(4, 3, 3)

In [19]:
a = np.random.random(size = (4, 3, 3, 3))
b = np.random.random(size = (3, 3, 3))

In [20]:
np.sum(a * b, axis = (1, 2, 3))

array([6.07841361, 7.04607303, 6.31236962, 7.71050025])

In [102]:
a = np.random.randint(0, 10, size = (10, 5, 6, 7)).astype('float32')

In [103]:
a

array([[[[5., 7., 1., ..., 7., 4., 1.],
         [2., 0., 8., ..., 7., 2., 6.],
         [6., 6., 1., ..., 1., 7., 2.],
         [8., 9., 5., ..., 3., 2., 0.],
         [6., 3., 9., ..., 7., 1., 5.],
         [0., 7., 4., ..., 1., 0., 9.]],

        [[2., 3., 9., ..., 8., 6., 4.],
         [2., 2., 5., ..., 5., 8., 3.],
         [5., 7., 7., ..., 5., 2., 4.],
         [1., 2., 6., ..., 2., 9., 9.],
         [0., 6., 0., ..., 2., 3., 2.],
         [8., 4., 4., ..., 3., 8., 9.]],

        [[0., 2., 1., ..., 1., 1., 4.],
         [0., 4., 3., ..., 3., 5., 9.],
         [3., 2., 8., ..., 7., 7., 6.],
         [5., 2., 9., ..., 6., 2., 7.],
         [2., 1., 0., ..., 1., 7., 3.],
         [2., 7., 9., ..., 8., 4., 3.]],

        [[2., 4., 5., ..., 2., 6., 0.],
         [1., 7., 8., ..., 9., 3., 8.],
         [3., 4., 7., ..., 0., 2., 6.],
         [7., 6., 9., ..., 9., 0., 8.],
         [2., 9., 2., ..., 7., 1., 6.],
         [0., 1., 4., ..., 4., 6., 6.]],

        [[0., 6., 7., ..., 4., 3

In [56]:
b = np.zeros(shape = (10, 5, 6, 3))
np.max(a[:, :, 1:3, 1:3], axis = (2, 3), keepdims = True).shape

(10, 5, 1, 1)

In [57]:
b[:, :, 1, 1] = np.max(a[:, :, 1:3, 1:3], axis = (2, 3))

In [64]:
b[:, :, 1, 1]

array([[0.96170676, 0.75269901, 0.97981527, 0.16186883, 0.802588  ],
       [0.4597008 , 0.85032604, 0.80556084, 0.70520008, 0.73046525],
       [0.55268279, 0.90034569, 0.79516413, 0.84382925, 0.73714192],
       [0.74366658, 0.87209443, 0.72724993, 0.59742786, 0.68675458],
       [0.83240537, 0.76850235, 0.95034751, 0.77147657, 0.94188299],
       [0.80881925, 0.59212397, 0.70807615, 0.83760574, 0.65532622],
       [0.97939185, 0.40710169, 0.82575894, 0.57960381, 0.98076573],
       [0.71485902, 0.83163434, 0.5006412 , 0.67542118, 0.85066214],
       [0.95298642, 0.90933102, 0.97005214, 0.96910267, 0.79876138],
       [0.93901186, 0.7599283 , 0.79963762, 0.91965329, 0.99252497]])

In [67]:
(a[:, :, 1:3, 1:3] == b[:, :, 1, 1].reshape(10, 5, 1, 1)).astype(int)

array([[[[0, 0],
         [1, 0]],

        [[1, 0],
         [0, 0]],

        [[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]],

        [[0, 0],
         [1, 0]]],


       [[[0, 0],
         [0, 1]],

        [[1, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 1],
         [0, 0]],

        [[0, 0],
         [1, 0]]],


       [[[0, 1],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 1]],

        [[0, 1],
         [0, 0]],

        [[0, 0],
         [1, 0]]],


       [[[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]],

        [[1, 0],
         [0, 0]],

        [[0, 1],
         [0, 0]],

        [[1, 0],
         [0, 0]]],


       [[[0, 1],
         [0, 0]],

        [[1, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[1, 0],
         [0, 0]],

        [[0, 0],
         [1, 0]]],


       [[[0, 1],
         [0, 0]],

        [[1, 0],
         [0, 0]],

        [[1, 0],
 

In [38]:
a.flatten()

array([0.6351941 , 0.59415432, 0.70517087, 0.0690868 , 0.00242459,
       0.22525423, 0.76530455, 0.04395865, 0.47152878, 0.85251169,
       0.92500746, 0.00973075, 0.9572178 , 0.05725347, 0.07306327,
       0.81297587])

In [39]:
a

array([[[[0.6351941 , 0.59415432],
         [0.70517087, 0.0690868 ]],

        [[0.00242459, 0.22525423],
         [0.76530455, 0.04395865]]],


       [[[0.47152878, 0.85251169],
         [0.92500746, 0.00973075]],

        [[0.9572178 , 0.05725347],
         [0.07306327, 0.81297587]]]])

In [68]:
ind = np.unravel_index(np.argmax(a, axis=None), a.shape)

In [69]:
ind

(9, 1, 2, 3)

In [75]:
a = np.array([[[2.0, 2.0], [3.0, 1.0]]])

In [76]:
ind = np.unravel_index(np.argmax(a, axis=None), a.shape)

In [77]:

ind

(0, 1, 0)

In [78]:
a

array([[[2., 2.],
        [3., 1.]]])

In [104]:
p_max = a[:, :, 1:3, 1:3].max(axis = (2, 3))

In [105]:
p_max.shape

(10, 5)

In [106]:
k = np.where(a[:, :, 1:3, 1:3] == p_max.reshape(10, 5, 1, 1))

In [107]:
k

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7,
        7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9]),
 array([0, 1, 1, 2, 3, 4, 0, 1, 1, 2, 3, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 2,
        3, 4, 0, 0, 0, 1, 2, 3, 4, 0, 1, 2, 2, 2, 3, 4, 0, 1, 2, 3, 4, 0,
        0, 1, 1, 2, 3, 4, 0, 1, 2, 3, 3, 4, 0, 1, 2, 3, 4]),
 array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0]),
 array([1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1]))

In [112]:
a[2, 3, 1:3, 1:3]

array([[8., 3.],
       [4., 9.]], dtype=float32)

In [113]:
a[2, 3, 1, 1] = 9.0

In [114]:
a[2, 3, 1:3, 1:3]

array([[9., 3.],
       [4., 9.]], dtype=float32)

In [115]:
a[2, 3, 1:3, 1:3] == p_max[2, 3]

array([[ True, False],
       [False,  True]])

In [117]:
ind = np.where(a[2, 3, 1:3, 1:3] == p_max[2, 3])

In [129]:
x_indices = ind[0]
y_indices = ind[1]

In [132]:
first_index = (x_indices[0] + 1, y_indices[0] + 1)

In [133]:
first_index

(1, 1)

In [134]:
a[2, 3, *first_index] = 98

In [135]:
a[2, 3, 1:3, 1:3]

array([[98.,  3.],
       [ 4.,  9.]], dtype=float32)